# kafka configuration
kafka:
  brokers:
    - "localhost:57351"
    - "localhost:57352"

# datasource configuration, support multiple datasource
# the first one must be 'default'
datasource:
  default:
    driver: sqlite3
    url: "file::memory:?cache=shared"
    max_idle: 10
    max_open: 100
    max_lifetime: 5 # minute
  slave:
    driver: sqlite3
    url: "file::memory:?cache=shared"
    max_idle: 10
    max_open: 100
    max_lifetime: 5 # minute
